version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: mydjangoapp:latest
    command: gunicorn VibeSync.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypass@db:5432/mydb

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass

volumes:
  postgres_data:
